CREATE TABLE IF NOT EXISTS Thanhvien248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    taikhoan VARCHAR(255) NOT NULL Unique,
    matkhau VARCHAR(255) NOT NULL,
    ten VARCHAR(255) NOT NULL,
    diachi VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    dt INT(10) NOT NULL,
    ghichu VARCHAR(255) NULL,
    PRIMARY KEY (id)
) ;

CREATE TABLE IF NOT EXISTS Nhanvien248 (
    Thanhvien248id INT(10) NOT NULL,
    vitri VARCHAR(255) NOT NULL,
    FOREIGN KEY (Thanhvien248id) REFERENCES Thanhvien248 (id) ON DELETE CASCADE ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS Khachhang248 (
    Thanhvien248id INT(10) NOT NULL,
    FOREIGN KEY (Thanhvien248id) REFERENCES Thanhvien248 (id) ON DELETE CASCADE ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS Lichhen248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    Khachhang248id INT(10) NOT NULL,
    ten VARCHAR(255) NOT NULL,
    dt VARCHAR(255) NOT NULL,
    thoigian TIMESTAMP NOT NULL,
    trangthai INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (Khachhang248id) REFERENCES Thanhvien248 (id) ON DELETE CASCADE ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS Dichvu248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    gia INT(30) NOT NULL,
    mota VARCHAR(255) NULL,
    PRIMARY KEY (id)
) ;

CREATE TABLE IF NOT EXISTS Phutung248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    gia INT(30) NOT NULL,
    soluong INT(30) NOT NULL,
    mota VARCHAR(255) NULL,
    PRIMARY KEY (id)
) ;

CREATE TABLE IF NOT EXISTS Hoadon248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    Khachhang248id INT(10) NOT NULL,
    NVBanhang248id INT(10) NOT NULL,
    thoigian TIMESTAMP NOT NULL,
    tongtien INT(30) NOT NULL,
    trangthai INT(10) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (Khachhang248id) REFERENCES Thanhvien248 (id) ON UPDATE CASCADE,
    FOREIGN KEY (NVBanhang248id) REFERENCES Thanhvien248 (id) ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS PhutungHoadon248 (
    Phutung248id INT(10) NOT NULL,
    Hoadon248id INT(10) NOT NULL,
    soluong INT(10) NOT NULL,
    gia INT(30) NOT NULL,
    PRIMARY KEY (Phutung248id, Hoadon248id),
    FOREIGN KEY (Phutung248id) REFERENCES Phutung248 (id) ON UPDATE CASCADE,
    FOREIGN KEY (Hoadon248id) REFERENCES Hoadon248 (id) ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS DichvuHoadon248 (
    Dichvu248id INT(10) NOT NULL,
    Hoadon248id INT(10) NOT NULL,
    soluong INT(10) NOT NULL,
    gia INT(30) NOT NULL,
    PRIMARY KEY (Dichvu248id, Hoadon248id),
    FOREIGN KEY (Dichvu248id) REFERENCES Dichvu248 (id) ON UPDATE CASCADE,
    FOREIGN KEY (Hoadon248id) REFERENCES Hoadon248 (id) ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS NVKithuatHoadon248 (
    NVKithuat248id INT(10) NOT NULL,
    Hoadon248id INT(10) NOT NULL,
    PRIMARY KEY (NVKithuat248id, Hoadon248id),
    FOREIGN KEY (NVKithuat248id) REFERENCES Thanhvien248 (id) ON UPDATE CASCADE,
    FOREIGN KEY (Hoadon248id) REFERENCES Hoadon248 (id) ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS Nhacungcap248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    dt VARCHAR(255) NOT NULL,
    mota VARCHAR(255) NULL,
    PRIMARY KEY (id)
) ;

CREATE TABLE IF NOT EXISTS Hoadonnhap248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    Nhacungcap248id INT(10) NOT NULL,
    thoigian TIMESTAMP NOT NULL,
    tongtien INT(30) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (Nhacungcap248id) REFERENCES Nhacungcap248 (id) ON UPDATE CASCADE
) ;

CREATE TABLE IF NOT EXISTS Phutungnhap248 (
    id INT(10) NOT NULL AUTO_INCREMENT,
    ten VARCHAR(255) NOT NULL,
    gia INT(30) NOT NULL,
    soluong VARCHAR(255) NOT NULL,
    Hoadonnhap248id INT(10) NOT NULL,
    Phutung248id INT(10) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (Hoadonnhap248id) REFERENCES Hoadonnhap248 (id) ON UPDATE CASCADE,
    FOREIGN KEY (Phutung248id) REFERENCES Phutung248 (id) ON UPDATE CASCADE
) ;
